// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyzgmlgbpbcyomlkvrrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5emdtbGdicGJjeW9tbGt2cnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjU2MjAsImV4cCI6MjA3NDMwMTYyMH0.hcn5kTDVXAgfMb9zsZ-1szt9QLEjfMatDfEjHyJk1_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});